//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LashApp.Data.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LashApp.Data.Scripts.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   SELECT 
        ///  a.[PayDate] &apos;Date&apos;,
        ///  t.[Name] &apos;Name&apos;,
        ///  t.[Price] &apos;Price&apos;
        ///  FROM Appointments a
        ///  JOIN Treatments t
        ///		ON a.TreatmentId = t.TreatmentId
        ///	LEFT JOIN Clients c
        ///		ON c.ClientId = a.ClientId
        ///  UNION ALL
        ///    Select 
        ///  pqc.[Date] &apos;Date&apos;,
        ///  p.[Name] &apos;Name&apos;,
        ///  p.[Price] * pqc.[QuantityChange] * (-1) &apos;Price&apos;
        ///  FROM ProductQuantityChanges pqc
        ///	JOIN Products p
        ///		ON p.ProductId = pqc.ProductId
        ///  WHERE 
        ///	pqc.IsPurchase = 1
        ///	.
        /// </summary>
        public static string GetFinancesReportDetails {
            get {
                return ResourceManager.GetString("GetFinancesReportDetails", resourceCulture);
            }
        }
    }
}
